site: Hyejin Kim - Digital Product Designer

url: https://hyejinni.github.io
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /works/:slug
  archives:
    output: true
    permalink: /archive/:slug
  resume:
    output: true
    permalink: /resume/:slug
    

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "archives"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "resume"
    values:
      layout: "post"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
  
sass:
  style: compressed

plugins:
  - jekyll-sitemap

paginate: 7
paginate_path: "/blog/page-:num/"