basic_settings:
  site_title: Hyejin
  favicon_image: /images/favicon.png

header_settings:
  logo_image: 
  logo_width: 100

menu_settings:
  menu_items:
    - title: 'Works'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Resume'
      url: 'https://github.com/hyejinni/hyejinni.github.io/raw/ca2b7dc50d08fbdb7c558506386b8bc1fea4a7b1/CV_HyejinKim.pdf'
# 나중에 아카이브 추가하고 싶으면 이부분 다시 살리면 됨
    # - title: 'Archive'
    #   url: '/archive/'


footer_settings:
  logo_image: 
  logo_width: 100
  tagline: Product Designer

hero_settings:
  background_image: 

post_settings:
  grid_spacing: 10

contact_settings:
  email_address: 'kimhj8463@gmail.com'
  form_action: 'https://formspree.io/xjvalypj'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Get in Touch'

social_settings:
  facebook_url: ''
  twitter_url: ''
  # instagram_url: 'https://www.instagram.com/chatty_pillow/'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: 'https://medium.com/@tangerines'
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: 'https://www.behance.net/hj_kim'
  deviantart_url: ''
  # github_url: 'https://github.com/hyejinni'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  # spotify_url: 'https://open.spotify.com/user/3144l3vgbreoyzxltwjjqi36htvu?si=8w7uvRsNQLOFAPKB4KpUSw'
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/jenny-hyejin-kim/'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#202224'
  text_medium_color: '#6C7A89'
  text_light_color: '#AEB3BB'
  accent_color: '#202224'
  border_color: '#ECEDEF'
  error_color: '#D64541'

font_settings:
  # 폰트 변경 여기에서
  font_embed: '<link href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.8/dist/web/static/pretendard.css","https://fonts.googleapis.com/css?family=Poppins:400,500,600,700|Ubuntu+Mono:400,700" rel="stylesheet">'
  title_font: 'Poppins, Pretendard, Helvetica, sans-serif'
  body_font: 'Pretendard, Poppins, Ubuntu Mono, sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 30
    medium_size: 30
    large_size: 30
    weight: 600
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 500
    letter_spacing: 0
  h1:
    size: 52
    size_small: 42
    weight: 500
    letter_spacing: -1.5
    letter_spacing_small: -1.2
    line_height: 64
    line_height_small: 48
  h2:
    size: 48
    size_small: 36
    weight: 500
    letter_spacing: -1.6
    letter_spacing_small: -1.04
    line_height: 56
    line_height_small: 44
  h3:
    size: 40
    size_small: 30
    weight: 600
    letter_spacing: -1.4
    letter_spacing_small: -0.54
    line_height: 48
    line_height_small: 36
  h4:
    size: 32
    size_small: 28
    weight: 600
    letter_spacing: -1
    letter_spacing_small: -0.6
    line_height: 36
  h5:
    small_size: 17
    medium_size: 24
    large_size: 28
    weight: 600
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 600
    letter_spacing: 0
    line_height: 1.6
  subtitle:
    size: 22
    size_small: 20
    weight_regular: 400
    weight_heavy: 500
    letter_spacing: 0.16
    letter_spacing_small: 0.2
    line_height: 32
    line_height_small: 28
  p:
    size: 18
    size_small: 17
    weight: 400
    letter_spacing: -0.009em
    letter_spacing_small: 0
    line_height: 32
  p_small:
    size: 16
    size_small: 15
    weight: 400
    letter_spacing: 0
    line_height: 24
  label:
    size: 14
    small_size: 12
    weight: 500
    letter_spacing: 0.8
    small_letter_spacing: 0.5
    line_height: 16
  footnote:
    size: 13
    weight: 400
    letter_spacing: -0.04
    line_height: 12
  blockquote:
      small_size: 14
      medium_size: 16
      large_size: 18
      weight: 500
      letter_spacing: -0.02
      line_height: 1.4
  buttons:
    weight: 500
    letter_spacing: 0.4
  figcaption:
    size: 12

advanced_settings:
  ajax_loading: true
  analytics_code: "G-3XFM2GDF2V"
  custom_styles: ""
  header_js: ""
  footer_js: ""